window.SUPABASE_URL  = 'https://sylkotirzlhrwybqelis.supabase.co';
window.SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5bGtvdGlyemxocnd5YnFlbGlzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTU0Nzg0OCwiZXhwIjoyMDk3MTIzODQ4fQ.xkvZNMJ75ukVrNRxybYmRu3hBaDnqiE4BeQteb2pUV8';
